### ISSUE TITLE
hasAllGraphs?

### ISSUE THREAD

**Issue by thinkt4nk** [nicholascloud/l33teral#4]
I love using the l33teral api.  `hasAllGraphs` is mentioned in the docs but it doesn't look like it's implemented.  Are you planning to implement it in the future?

**Comment by thinkt4nk** [comment]
Ah, I guess this might be synonymous with `probeAll`?

**Comment by nicholascloud** [comment]
Hi @thinkt4nk, thanks for the kind words! 

Yes, in commit 49cc1de2d91989d69e2befa169ce513410885153: `renamed `hasAll|AnyGraphs` to `probeAll|Any`; added license`. 

Good catch, though -- I will update the README pronto to eliminate confusion!

**Comment by nicholascloud** [comment]
pushed readme correction; pushed tag v2.0.5; published npm update
